### ISSUE TITLE
SSL检查出错

### ISSUE THREAD

**Issue by CNMan** [lusaisai/FindMeGoogleIP#1]
在Debian7上安装了python3，SSL检查的时候全是这个错误，最后No available servers found

``` python
Exception in thread Thread-20638:
Traceback (most recent call last):
  File "/usr/lib/python3.2/threading.py", line 740, in _bootstrap_inner
    self.run()
  File "FindMeGoogleIP/trunk/findmegoogleip.py", line 115, in run
    conn = ssl.create_default_context().wrap_socket(socket.socket(), server_hostname="www.google.com")
AttributeError: 'module' object has no attribute 'create_default_context'
```

**Comment by lusaisai** [comment]
create_default_context是python3.4新的feature，3.2可以把下面一段

``` python
conn = ssl.create_default_context().wrap_socket(socket.socket(), server_hostname="www.google.com")
conn.connect((self.ip, self.port))
```

改为

``` python
context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
context.set_default_verify_paths()
context.verify_mode = ssl.CERT_REQUIRED
conn = context.wrap_socket(socket.socket())
conn.connect((self.ip, self.port))
ssl.match_hostname(conn.getpeercert(), 'www.google.com')
```

**Comment by CNMan** [comment]
多谢，nslookup时能否添加更多本地域名？最好能从外部文件中自定义，谢谢
http://www.google.com/supported_domains

**Comment by lusaisai** [comment]
不客气。

你是想要同时查找多个域名下的IP吗？如果是这样的话，只要在命令行添加参数就好了。可以建一个alias保存。

``` bash
./findmegoogleip.py hk mo tw jp kr la vn th
```

不是很清楚你的问题，如果误解了，请详细描述一下。

**Comment by CNMan** [comment]
现在的参数是指定dns的，我直接用all了
我是想第59行的google.com能不能变成把google的那些域名循环一次

**Comment by lusaisai** [comment]
明白你的意思了，但我想暂时先不支持这个功能。
这个script主要是寻找全球各地的google服务器地址，比如说“./findmegoogleip.py tw”返回的ip都是台湾的，你所说的功能，按理说会返回一些其他地区的ip，比如说美国的，如果真需要美国的ip，可以直接跑“./findmegoogleip.py us”，所以这里有些重复劳动。
目前效果挺好的，不知道你那边网络情况怎么样，我自己一直只找韩国和台湾的ip，花个一分钟跑一下，能有上百个ip，速度都很快。

我会把这个issue关了，如果以后有问题的话，再开issue讨论吧。

**Comment by CNMan** [comment]
好的，还是多谢了:)

**Comment by CNMan** [comment]
能不能把nslookup -q=TXT _netblocks.google.com 8.8.8.8的结果全过滤掉?谢谢
64.18.0.0/20
64.233.160.0/19
66.102.0.0/20
66.249.80.0/20
72.14.192.0/18
74.125.0.0/16
173.194.0.0/16
207.126.144.0/20
209.85.128.0/17
216.58.208.0/20
216.239.32.0/19
现在只过滤了74和173开头的：https://github.com/lusaisai/FindMeGoogleIP/blob/master/findmegoogleip.py#L224

**Comment by lusaisai** [comment]
okay.

**Comment by CNMan** [comment]
两个异常:

``` python
Exception in thread Thread-26097:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "FindMeGoogleIP/trunk/findmegoogleip.py", line 164, in run
    conn.connect((self.ip, self.port))
  File "/usr/lib/python3.4/ssl.py", line 840, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.4/ssl.py", line 827, in _real_connect
    socket.connect(self, addr)
OSError: [Errno 113] No route to host
```

``` python
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "FindMeGoogleIP/trunk/findmegoogleip.py", line 192, in run
    answer = self.resolver.query(self.name)
  File "/usr/local/lib/python3.4/dist-packages/dns/resolver.py", line 834, in query
    source_port=source_port)
  File "/usr/local/lib/python3.4/dist-packages/dns/query.py", line 230, in udp
    one_rr_per_rrset=one_rr_per_rrset)
  File "/usr/local/lib/python3.4/dist-packages/dns/message.py", line 791, in from_wire
    reader.read()
  File "/usr/local/lib/python3.4/dist-packages/dns/message.py", line 732, in read
    self._get_section(self.message.additional, adcount)
  File "/usr/local/lib/python3.4/dist-packages/dns/message.py", line 704, in _get_section
    self.message.origin)
  File "/usr/local/lib/python3.4/dist-packages/dns/rdata.py", line 477, in from_wire
    return cls.from_wire(rdclass, rdtype, wire, current, rdlen, origin)
  File "/usr/local/lib/python3.4/dist-packages/dns/rdtypes/IN/AAAA.py", line 51, in from_wire
    wire[current : current + rdlen])
  File "/usr/local/lib/python3.4/dist-packages/dns/inet.py", line 70, in inet_ntop
    return dns.ipv6.inet_ntoa(address)
  File "/usr/local/lib/python3.4/dist-packages/dns/ipv6.py", line 34, in inet_ntoa
    raise ValueError("IPv6 addresses are 16 bytes long")
ValueError: IPv6 addresses are 16 bytes long
```

**Comment by lusaisai** [comment]
是对每一个DNS Server查询都会出错，还是只对某些个DNS Server查询时出错？

**Comment by CNMan** [comment]
偶尔出现...

**Comment by lusaisai** [comment]
可能是DNS Server返回的数据有问题。

**Comment by CNMan** [comment]
IP快死完了:(

**Comment by lusaisai** [comment]
嗯，随机应变吧。
